# This code summarises all data values across Events for individual participants

```{r}

rm(list = ls())

# Let the user select the file to import
file_path <- file.choose()

# Read the data
library(readr)
data <- read.csv(file_path, check.names = FALSE)

# Remove the "File Name" column
library(dplyr)
# data <- data %>%
#   select(-`File Name`)

# Identify the numeric columns (excluding "File Name" and "Event")
numeric_columns <- setdiff(names(data)[-c(1, 2)], c("Event"))

# Convert numeric columns to numeric
data <- data %>%
  mutate_at(vars(numeric_columns), as.numeric)

# Group by 'Event' and calculate mean for each numeric column
Means <- data %>%
  group_by(Event) %>%
  summarise(across(where(is.numeric), mean, na.rm = TRUE, .names = "{.col}"))

# Group by 'Event' and calculate standard deviation for each numeric column
SD <- data %>% 
  group_by(Event) %>%
  summarise(across(where(is.numeric), sd, na.rm = TRUE, .names = "{.col} SD"))

# Combine Means and SD data frames
summary_data <- cbind(Means, SD)

# Remove 2nd "Event" column
summary_data <- summary_data %>%
 select(-39)

# Define order of "Event"
custom_order <- c("BFC", "FFC", "MAW", "BR", "EFT", "Min", "Max")

# Convert the "Event" column to a factor with custom levels
summary_data$Event <- factor(summary_data$Event, levels = custom_order)

# Order the data frame by the "Event" column
summary_data <- summary_data[order(summary_data$Event), ]


# Create a new column with the participant's code
base_file_name <- tools::file_path_sans_ext(basename(file_path)) # Extract base file name without extension
base_file_name <- sub(" - Combined$", "", base_file_name) # remove "- Combined" from the end of the base file name
summary_data$`File Name` <- base_file_name

# Re-order data frame
summary_data <- summary_data %>%
  select(`File Name`, everything())

rm(data, Means, SD, custom_order, numeric_columns)

```

```{r}
# Generate the dynamic file name
output_file <- paste0("C:/Users/billy/OneDrive/Documents/Auburn/Sports Medicine & Movement Lab/PhD Thesis/Data/Pilot/", base_file_name, " - Means and SDs.csv")

# Write 'summary_data' to a CSV file
write.csv(summary_data, output_file, row.names = FALSE)

rm(base_file_name, file_path, output_file)
```





